# Generated by Django 5.2.7 on 2025-12-01 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CyberScamStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('category', models.CharField(max_length=50)),
                ('direct_trade', models.IntegerField()),
                ('shopping_mall', models.IntegerField()),
                ('game', models.IntegerField()),
                ('email_trade', models.IntegerField()),
                ('romance', models.IntegerField()),
                ('investment', models.IntegerField()),
                ('etc', models.IntegerField()),
            ],
            options={
                'unique_together': {('year', 'category')},
            },
        ),
        migrations.CreateModel(
            name='TravelStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('country', models.CharField(default='TOTAL', max_length=255)),
                ('departures', models.IntegerField()),
            ],
            options={
                'unique_together': {('year', 'month', 'country')},
            },
        ),
        migrations.CreateModel(
            name='VoicePhishingStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('cases', models.IntegerField()),
            ],
            options={
                'unique_together': {('year', 'month')},
            },
        ),
    ]
