# Generated by Django 5.2.8 on 2025-12-02 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='travelstat',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='travelstat',
            name='country_name',
            field=models.CharField(blank=True, help_text='국가명 (예: 일본, 미국 등)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='travelstat',
            name='ed_cd',
            field=models.CharField(default='D', help_text='D=국민 해외관광객(출국), E=방한 외래관광객(입국)', max_length=1),
        ),
        migrations.AddField(
            model_name='travelstat',
            name='ratio',
            field=models.FloatField(blank=True, help_text='전년 동월 대비 증감률(%) (없으면 NULL)', null=True),
        ),
        migrations.AlterField(
            model_name='travelstat',
            name='country',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='travelstat',
            name='departures',
            field=models.IntegerField(help_text='출국자 수 (num 필드)'),
        ),
        migrations.AlterUniqueTogether(
            name='travelstat',
            unique_together={('year', 'month', 'country', 'ed_cd')},
        ),
    ]
